// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxoff1YB_Qw_xTVnkmqJ6QwC0aF5NWYzQ',
    appId: '1:169551218022:web:d552f8195a5822bea634a7',
    messagingSenderId: '169551218022',
    projectId: 'mentra-firebase',
    authDomain: 'mentra-firebase.firebaseapp.com',
    storageBucket: 'mentra-firebase.appspot.com',
    measurementId: 'G-GR9TW1HLCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jcLDGIt_1RMz6f07FV6We0C4KkgUqBU',
    appId: '1:169551218022:android:9f799b6f445beb9ca634a7',
    messagingSenderId: '169551218022',
    projectId: 'mentra-firebase',
    storageBucket: 'mentra-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa1KBp0f_ro54lk-_x0vwDDjxFA1lEOss',
    appId: '1:169551218022:ios:1aee780eb6a35b4da634a7',
    messagingSenderId: '169551218022',
    projectId: 'mentra-firebase',
    storageBucket: 'mentra-firebase.appspot.com',
    iosBundleId: 'com.yourmentra.mentra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa1KBp0f_ro54lk-_x0vwDDjxFA1lEOss',
    appId: '1:169551218022:ios:f90535e650636af2a634a7',
    messagingSenderId: '169551218022',
    projectId: 'mentra-firebase',
    storageBucket: 'mentra-firebase.appspot.com',
    iosBundleId: 'com.mentra.app.mentra.RunnerTests',
  );
}
